spring.application.name=antrepbo2
server.port=${PORT:9999}

# ====================================================
# KONFIGURASI DATABASE SUPABASE (POSTGRESQL)
# ====================================================
# Tambahkan ?prepareThreshold=0 di akhir URL ini:
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.kyerjyamptipjcqwvxhv
spring.datasource.password=${DB_PASSWORD}

# Pengaturan Hibernate / JPA untuk PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Mematikan fitur yang memicu error koneksi
spring.jpa.open-in-view=false

# Konfigurasi agar pool koneksi lebih stabil
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000