spring.application.name=antrepbo2
server.port=${PORT:9999}

# ====================================================
# KONFIGURASI DATABASE SUPABASE (POSTGRESQL)
# ====================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.kyerjyamptipjcqwvxhv
spring.datasource.password=${DB_PASSWORD}

# Pengaturan Hibernate / JPA untuk PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true