spring.application.name=antrepbo2

server.port=9999

spring.datasource.url=jdbc:h2:file:./data/antredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=antree
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true